export enum CategoriaReclamo {
  MI_CUENTA = 'MI_CUENTA',
  BUGS_ERRORES = 'BUGS_ERRORES',
  PEDIDOS = 'PEDIDOS',
  ESTETICA_UX = 'ESTETICA_UX',
  OTROS_USUARIOS = 'OTROS_USUARIOS',
  OTROS = 'OTROS'
}